# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WeiBoAir' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeiBoAir
  use_frameworks!
  pod “AFNetworking”
  pod 'SDWebImage', '~>3.8'
  pod “YYModel”
  pod “FMDB”
  pod “SVProgressHUD”
  pod “pop”
  pod 'SwiftyJSON', '~> 4.0'
  pod 'HandyJSON', '~> 4.1.1'
  pod 'Alamofire', '~> 4.7'
end
